# Generated by Django 4.1.3 on 2023-09-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('NA', 'North America'), ('LA', 'South America'), ('OC', 'Oceania'), ('AF', 'Africa')], db_index=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_type', models.TextField()),
                ('PM_type', models.TextField()),
                ('pro_variant', models.TextField()),
                ('variant', models.TextField()),
                ('varclass', models.CharField(choices=[('NA', 'NoArg'), ('SN', 'SNP'), ('ST', 'SNP Stop'), ('SS', 'SNP Silent'), ('DE', 'Deletion'), ('DF', 'Deletion Frameshift'), ('DT', 'Deletion Stop'), ('EX', 'Extragenic'), ('IN', 'Insertion'), ('IF', 'Insertion Frameshift'), ('IT', 'Insertion Stop')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('lineage', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('annotation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('sample', models.TextField()),
                ('time', models.TimeField(db_index=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.country')),
                ('lineage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lineage')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpos', models.PositiveIntegerField()),
                ('rvar', models.TextField()),
                ('qvar', models.TextField()),
                ('qpos', models.PositiveIntegerField()),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.extra')),
                ('protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.protein')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sample')),
            ],
        ),
    ]
