# Generated by Django 4.1.3 on 2023-09-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='segment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.species'),
        ),
    ]
