# Generated by Django 4.1.3 on 2023-09-04 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_species_sample_segment_sample_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='extra',
        ),
        migrations.AddField(
            model_name='extra',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
    ]
