# Generated by Django 4.1.3 on 2023-09-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_position_extra_extra_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
