# Generated by Django 4.1.3 on 2023-09-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_country_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='annotation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='refseq',
            field=models.TextField(null=True),
        ),
    ]
