# Generated by Django 4.1.3 on 2023-09-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_protein_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='species',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.species'),
        ),
    ]
