# Generated by Django 4.1.3 on 2023-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_protein_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='time',
            field=models.DateField(db_index=True),
        ),
    ]
