# Generated by Django 4.1.3 on 2023-10-13 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_protein_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='protein',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
    ]
