# Generated by Django 4.1.3 on 2023-10-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_position_protein_delete_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(db_index=True, max_length=32)),
                ('annotation', models.TextField()),
                ('species', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.species')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.protein'),
        ),
    ]
