# Generated by Django 4.1.3 on 2023-11-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lineage_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='time',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
