# Generated by Django 4.1.3 on 2023-12-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_species_seglength'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
