# Generated by Django 4.1.3 on 2024-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_protein_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='segment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
