# Generated by Django 4.2.11 on 2024-03-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_protein_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='position',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='protein',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.protein'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sample',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='app.sample'),
        ),
    ]
