# Generated by Django 4.1.3 on 2024-03-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_extra_id_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.protein'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sample'),
        ),
    ]
