# Generated by Django 4.1.3 on 2024-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_extra_position_alter_position_protein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='nested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
