# Generated by Django 3.2.16 on 2024-04-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_protein_nested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='nested',
        ),
    ]
